### PR TITLE
Use the new DHIS2 color palette in an MUI theme

### PR DESCRIPTION
**Pull request by amcgee**
This PR accomplishes a few things, chief among them being :

**Implement an MUI Theme which exposes the [DHIS2 color palette](https://projects.invisionapp.com/share/A7LT4TJYETS#/screens/302550228_Color) created by @joeDHIS.**

I made educated guesses based on standard UX patterns and some inferences from Joe's various mockups to assign palette colors to MUI-aware theme elements (see [`dhis2.theme.js`](https://github.com/dhis2/maps-app/pull/27/files#diff-3dfed8de7ec7d5127b461aad380d38db)).  Future work will be to implement intelligent base components (buttons, text fields, etc.) to use the theme to match our desired look and feel.

**Known issue** Unfortunately, we're actually using TWO versions of material UI currently - this change addresses Material UI v3 which we use in maps-app, but the included components from d2-ui (notably the file menu) have not yet been updated from an older Material UI version and so they aren't affected by this change.  This also means that until d2-ui is updated we need to include TWO different copies of `<MuiThemeProvider>` in `App.js`.  Hopefully we can upgrade d2-ui to utilize the new MUI and standardize on this theme.

The net UI changes are relatively small and mostly involve subtle color tweaks with some rewiring under the hood.  Additional updates I made in going through the various places throughout the code where :

1) Set up MUI defaults to match colors from the palette (see [`dhis2.theme.js`](https://github.com/dhis2/maps-app/pull/27/files#diff-3dfed8de7ec7d5127b461aad380d38db))
2) Remove hardcoded color values from the maps app wherever possible.  There are certainly some remaining
3) Update the 
4) Update the shadows and dividers in the header and sidebar to match, as closely as possible, [this sample](https://projects.invisionapp.com/share/E2O15NQMDCX#/screens/322019629_Empty_State) without changing too much about the maps app design layout (I.e. no new logo, secondary menu bar is not white)
5) Change the "selected" highlight color in basemap selector, Org Unit panel, and Event->style panel to be the `accentSecondaryLight` color (blue-green-ish #48A999).  See screenshots below.
6) Update the styling of the Event Layer filter elements to be a little cleaner and match the new colors.  Still needs more design work (see screenshot below).
7) _minor_ Center the text under basemap images
8) _minor_ Remove `ItemSelect.css`, moving styles into `ItemSelect.js`

**5 - BASEMAP SELECTION BEFORE (2.30)**

screen shot 2018-09-27 at 2 18 11 pm

**5 - BASEMAP SELECTION AFTER** - note also the subtle update to opacity slider color which automagically matches the Primary Accent we defined in the theme.

screen shot 2018-09-27 at 2 18 21 pm

**6 - FILTER ROW BEFORE (2.30)**

screen shot 2018-09-27 at 11 55 25 am

**6 - FILTER ROW AFTER**

screen shot 2018-09-27 at 11 55 20 am

**Overall UI 2.30 (Old Material UI version)**

screen shot 2018-09-27 at 2 25 03 pm

**Starting UI Dev (Material UI 3)**

screen shot 2018-09-27 at 2 24 40 pm

**Starting UI After change** - Note the subtle background color changes and slightly-updated header bar

screen shot 2018-09-27 at 2 25 11 pm

### CODE REVIEW

**Comment by amcgee** [comment]
There's a JIRA issue associated with this PR, but since JIRA is down I have no idea what that number is ;-)

**Comment by turban** [comment]
Nice work @amcgee! Good to centralize the style theme in one file. The code looks fine. I would like joe to review the screenshots.

A few for minor issues that I will leave for joe to decide: 

The layers drawer shadows looks darker than the other shadows: 
skjermbilde 2018-09-27 kl 16 04 12

Should we use darker text for layer names as the information is quite important?
skjermbilde 2018-09-27 kl 16 04 24

We don't use rounded corners a lot in our design - should we use it for filters? 
skjermbilde 2018-09-27 kl 16 04 49

**Comment by amcgee** [comment]
Thanks for the comments @turban!

I can go either way on the rounded corners, I added them and a border but we could keep them square (or a more subtle round, 4px instead of 8px) if we have the border.

I wanted to differentiate it from the normal UI elements since it's kind of a raised, repeatable content like a card or a pill (which both have rounded corners).  We could actually use a `<Card>` here if we wanted, I just went with the most minimal change.

**Comment by joeDHIS** [comment]
Overall this looks great. Here are some changes I would like make, mostly for consistency for other apps and a few accessibility things:

1. Change the border for selected basemaps to 3px solid $accent-primary
screen shot 2018-09-28 at 09 57 36

2. Change the text for selected basemaps to Roboto Medium $accent-primary-dark

3. For layer titles in the "Add Layer" popover, let's use $grey-dark

4. For filter "cards" inside the modal: Radius: 4px, Border: 1px solid $grey-light, Background: #FCFCFC. I'd also suggest using the Trash icon for deletion.
screen shot 2018-09-28 at 09 59 24

5. For consistency, let's use a white background toolbar for the "File" menu and "Add layer", as we do in Dataviz.

6. I'd like to make some changes to the "toolbar" in the layer card, including using $grey-dark for all controls, here is the specs:
screen shot 2018-09-28 at 10 06 16


(Note: Generally speaking, I try to avoid using $grey for text. The contrast ratio is just not good enough to make it accessible for all (visual impairments, sun shining on screen etc.). The lightest I usually use for text is $grey-dark for anything that is even semi-important.)

Awesome job with these UI changes @amcgee , great to move towards consistency in all apps. Thanks for the initiative.

**Comment by amcgee** [comment]
Thanks @joeDHIS, I really like these changes and will take a stab at them shortly!

My goal generally is to remove app-level customization wherever possible so we settle on a standard, modular set of components which will automatically pick up the theme.  A few questions for what to include in that theme:

1) Should dividers (like the ones in the header bar and above the layer card toolbar) be `1px solid $grey-light`?  I am currently using `#202020 15%` for all dividers which I grabbed [here](https://projects.invisionapp.com/share/A7LT4TJYETS#/screens/306822640).

2) Is #FCFCFC a standard background color we should store in the theme palette?  If so what should we call it?  In what situations should it be used?  I'm using `$snow` (`#F4F6F8` which is very similar to `#FCFCFC`) as the default background, `$white` as the standard background for first-level UI elements, and `$blue-grey` for menus (though that's probably going away).

3) Where do you envision `$blue-grey` being used if not as the background for menus?  Currently that's the only place I have it in the Mui theme, and we're replacing that with white.

4) What colors would you recommend for primary, secondary, and disabled text?  Currently I'm using `$grey-black`, `$grey`, and `$grey-light` respectively, but I agree that `$grey` and lighter don't contrast enough in some cases.  We could do `$black`, `$grey-black`, `$grey` but I don't know that `$black` and `$grey-black` are far enough apart for that and in web dev I think off-black tends to provides better text readability.

5. In the basemap card I'm using the standard divider color `#202020 15%` for the border of non-selected images.  Should this be $grey-light as it appears in your image?

**Comment by joeDHIS** [comment]
Hey @amcgee 

I totally agree on the standardisation of a theme - this is our goal with d2ui right now. It is a rocky road due to the side-by-side development with new apps, but the goal is to have standardised elements and a minimum of in-app customisation. Regarding your points:

1. Yes, $grey-light is the default color used for line dividers and such things.

2. #FCFCFC is not a standard background color...yet. I have used it here, and there is one other instance of it in use in data-visualizer. Right now it's in limbo, possibly going to be added to the next version of the color theme file defined in d2ui. As you said, $snow is the default bg color unless specified otherwise.

3. $blue-grey is rarely used, mostly in Capture app, but it may be phased out of the next theme version. I don't think we use it anywhere in GIS or Dataviz. Will keep this in the back of my head.

4. Indeed! The pattern set up initially was $black for primary, $grey-dark for secondary and $grey for disabled. We can't go any lighter on $grey-dark and still meet WCAG AAA contrast levels, so I think we have to stick with this. Instead of color, we should always be using size/position to reinforce the information hierarchy. (Agree $black readability, it got carried over from Material Design. Will be updated eventually in the main d2ui theme).

5. Yup, go for $grey-light on that.

I hope those answers were clear, some of them were a little bit fuzzy, and I think that's due to the parallel dev of new apps and d2ui. Let me know if there's anything unclear/inconsistent and I'll take a look.

**Comment by turban** [comment]
Minor: could we remove the rounded corners when hovering menu items? 

skjermbilde 2018-10-04 kl 11 06 47

**Comment by amcgee** [comment]
One last question @joeDHIS - what color should we use for ":hover" states, such as when hovering over the "remove filter" button in the screenshot below?

screen shot 2018-10-04 at 4 12 13 pm

This is using $grey-light but it might not be great to exactly match the border color?

**Comment by joeDHIS** [comment]
@amcgee - Let's use $accent-primary-lightest there, and let's show a "Delete filter" tooltip too please 😈

**Comment by amcgee** [comment]
Here's the latest screenshot with the input from @joeDHIS 👍 (for review)

screen shot 2018-10-04 at 4 17 10 pm

I also removed the rounded corners on `Add Layer` and `Interpretations` menu buttons.  The File menu button still has rounded corners, but that comes from a shared component so I didn't want to make an override just yet.

screen shot 2018-10-04 at 4 18 31 pm

screen shot 2018-10-04 at 4 18 46 pm

screen shot 2018-10-04 at 4 18 52 pm

**Comment by amcgee** [comment]
@joeDHIS done

screen shot 2018-10-04 at 4 36 18 pm

**Comment by amcgee** [comment]
@turban @joeDHIS let me know if there are any other changes or if this is good to go!

**Comment by joeDHIS** [comment]
Looks good. Thumbs up from me. 👍

**Comment by turban** [comment]
Good work @amcgee! Will take a closer look before Monday :-)

**Comment by turban** [comment]
@joeDHIS / @edoardo - should we have rounded corners for main menu items or not?

**Comment by turban** [comment]
I have merged this PR - it looks nice and we can always make smaller adjustments later.

**Comment by joeDHIS** [comment]
> @joeDHIS / @edoardo - should we have rounded corners for main menu items or not?

@turban - The Update button has rounded corners, as does the 'Interpretations' toggle button. The File/Options/Download menu items are squared. (This theoretically works in my head for buttons vs. menu items, but open to change if it ends up looking weird)

**Comment by amcgee** [comment]
@joeDHIS I agree theoretically it works, but I think I'm pro-square in the context of a toolbar.  The bar is a rectangle, so having rounded corners within a rectangular context (and without any padding between the rounded button and the squared container) doesn't fit for me.  Here's what the Add Layers button previously looked like (rounded corners with a `border-right`) in 2.30:

screen shot 2018-10-09 at 11 31 12 am

In dev I've switched this to a straight line spacer between the Add Layer button and the rest of the menu (as in your mockups also) but the file menu item is rounded on hover which feels inconsistent.  I do think the update button needs to be rounded though, so maybe the answer is different padding and margin around the File menu button in the toolbar?  I'm also sure there's some prior work out there we could reference to see what looks good.  Have people done rounded horizontal toolbar menus before?

**Comment by joeDHIS** [comment]
@amcgee - Not sure if I'm misunderstanding, but I think we agree? I was thinking:
Update: rounded
File: squared
Interpretations toggle: rounded.
I took inspiration from the Google Docs toolbar for this, see screenshot:
screen shot 2018-10-09 at 12 14 37

Is that what you are also in favour of? I'm a little mixed up here.

**Comment by amcgee** [comment]
Yes I think we're mostly on the same page!  The FileMenu will probably have to be a change in `d2-ui` if we want to make it squared.

For the interpretations toggle we're currently squared in Maps, you think it should be rounded?

**Pull request merged**
