### PR TITLE
DHIS2-4917 - Support start/end date periods for thematic layers

### PR DESCRIPTION
**Pull request by amcgee**
There's a lot of duplication and inline style usage in EventDialog, ThematicDialog, and TrackedEntityDialog - we should refactor them.  For now I added support for start/end periods to Thematic layers and added error handling to Event and TrackedEntity layers which previously would break silently when an invalid date was entered.

### CODE REVIEW

**Comment by turban** [comment]
We should also check if end date is later that start date (web api error if not)

**Comment by amcgee** [comment]
Pushed another minor update to remove the default value (malformed string, was never used and caused a console warning).  Ready to merge if that minor change is approved

**Comment by amcgee** [comment]
There's also a theme issue causing large body texts which I will fix separately

**Comment by amcgee** [comment]
Going to go ahead and merge since it was a minor change 👍

**Pull request merged**
