### PR TITLE
chore: upgrade to app-platform and new plugin architecture

### PR DESCRIPTION
**Pull request by jenniferarnesen**
https://dhis2.atlassian.net/browse/DHIS2-4816

* `public` folder is removed as that doesn't fit with new architecture. The i18n_old had translations for the old Translate and Share dialogs that have been replaced and are no longer in use
* Entry point for the app is src/AppWrapper.js. This replaces app.js and Root.js
* Entry point for plugin is PluginWrapper.js. This file is identical to the same file in DV and LineList.
* Functionality for the old map.js (for the plugin) is now handled by plugin/MapContainer.js
* The old plugin/Plugin.js file has been renamed to plugin/Map.js (this code is unchanged)
* The file named plugin/Plugin.js is simply a thin wrapper that provides the D2Shim and the SystemSettingsProvider.
* Only change in AppLayout is to remove HeaderBar since that is now provided by the platform
* Removed FatalBoundaryError since that is provided by platform
* util/api.js - need to use d2 to get the baseUrl instead of `config`

How to try it out
- to run the app, use the typical steps (yarn install, yarn start)
- to try the plugin, you currently have to use it from dashboard. Follow these steps:

1. get dashboard branch `feat/map-plugin-latest`
2. in browser add the plugin override (this is for dev mode only) that looks like this:  
image
3. get this maps-app branch `chore/upgrade-to-app-platform`
4. start the dashboard on localhost:3000 `DHIS2_BASE_URL=https://debug.dhis2.org/dev yarn start`
5. start the maps-app. The app will be on localhost:3001 and the plugin on localhost:3002.  `DHIS2_BASE_URL=https://debug.dhis2.org/dev yarn start`
6. Open localhost:3000. If you use debug/dev, then you can go straight to `http://localhost:3000/#/jdCDW9aTIba` to get a dashboard with a single map on it.

### CODE REVIEW

**Comment by turban** [comment]
Small style issue in header bar: 

Screenshot 2023-03-01 at 12 41 35

**Comment by turban** [comment]
App bug: Facility icons don't load: 

Screenshot 2023-03-01 at 14 57 09

Screenshot 2023-03-01 at 14 57 23

**Comment by turban** [comment]
Map labels don't show:

Screenshot 2023-03-01 at 15 01 06

Font URL seems to be wrong (undefined): http://localhost:3001/undefined/dhis-web-maps/fonts/Open%20Sans%20Regular/0-255.pbf

**Comment by jenniferarnesen** [comment]
> Map labels don't show:
> 
> Screenshot 2023-03-01 at 15 01 06
> 
> Font URL seems to be wrong (undefined): http://localhost:3001/undefined/dhis-web-maps/fonts/Open%20Sans%20Regular/0-255.pbf

The url has been fixed. Once in production, the domain will be the same, thus resolving this CORS issue

**Comment by turban** [comment]
> Small style issue in header bar:

Pushed a small fix to the vertical scroll bar issue reported above.

**Review by turban — APPROVED** [review]
Good work!

**Pull request merged**
